com.rolla.musicplayer.core.model.Song
com.rolla.musicplayer.core.model.Album
com.rolla.musicplayer.core.model.Artist
com.rolla.musicplayer.core.model.Playlist
com.rolla.musicplayer.core.model.EqualizerPreset
